### ISSUE TITLE
Can´t find ticket

### ISSUE THREAD

**Issue by RenatoGregio** [kairoaraujo/PowerAdm#24]
After created a ticket and save without execute, poweradm can´t find the ticket again to execute:

Please choose an option: 2

[LPAR creation]

Select the Change/Ticket to execute:

Traceback (most recent call last):
  File "/home/poweradm/PowerAdm/poweradm.py", line 33, in <module>
    main_poweradm()
  File "/home/poweradm/PowerAdm-0.8.4-beta/poweradm/poweradm.py", line 62, in main_poweradm
    exec_findlpar.selectChange()
  File "/home/poweradm/PowerAdm-0.8.4-beta/poweradm/findchange.py", line 47, in selectChange
    listChanges = fnmatch.filter(os.listdir("poweradm/changes/"), "*.sh")
OSError: [Errno 2] No such file or directory: 'poweradm/changes/'

**Comment by kairoaraujo** [comment]
Release 0.8.5-beta is OK for this bug.;:
