### ISSUE TITLE
Erro ao salvar a configuração da nova LPAR

### ISSUE THREAD

**Issue by Rafa-Dias** [kairoaraujo/PowerAdm#35]
Está criando uma LPAR sem SCSI e utilizando NPIV

The configuration of last LPAR is OK?(y/n): y
Writing file teste-10252016-154543.sh ...
Traceback (most recent call last):
  File "./poweradm.py", line 45, in <module>
    main_poweradm()
  File "/home/poweradm/PowerAdm-TVS-SP/poweradm/menu.py", line 79, in main_poweradm
    createlparconf.exec_createlparconf()
  File "/home/poweradm/PowerAdm-TVS-SP/poweradm/createlparconf.py", line 453, in exec_createlparconf
    newchange.writechange()
  File "/home/poweradm/PowerAdm-TVS-SP/poweradm/mklparconf.py", line 682, in writechange
    wchg_lpar_fc()
  File "/home/poweradm/PowerAdm-TVS-SP/poweradm/mklparconf.py", line 464, in wchg_lpar_fc
    self.veth, self.vios1, vhba_vio1, self.vios2,
NameError: global name 'vhba_vio1' is not defined

**Comment by Rafa-Dias** [comment]
Segue novo erro

Getting free virtual slots to be used, please wait...
Checking if all virtual devices are free to use. Please wait...

The configuration of last LPAR is OK?(y/n): y
Writing file teste-10252016-155957.sh ...
Traceback (most recent call last):
  File "./poweradm.py", line 45, in <module>
    main_poweradm()
  File "/home/poweradm/PowerAdm-TVS-SP/poweradm/menu.py", line 79, in main_poweradm
    createlparconf.exec_createlparconf()
  File "/home/poweradm/PowerAdm-TVS-SP/poweradm/createlparconf.py", line 453, in exec_createlparconf
    newchange.writechange()
  File "/home/poweradm/PowerAdm-TVS-SP/poweradm/mklparconf.py", line 717, in writechange
    file_reservedslots_tmp.write('%s\n%s\n' % (vios1_vslot_vscsi,
NameError: global name 'vios1_vslot_vscsi' is not defined
